version: 2

references:
  elixir_image: &elixir_image
    docker:
      - image: circleci/elixir:1.9.2-node
        environment:
          MIX_ENV: test
          POSTGRES_USER: postgres
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_DB: pay_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:

  undeploy_image: &undeploy_image
    docker:
      - image: circleci/elixir:1.9.2

  cf_install: &cf_install
    run:
      command: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
        mkdir -p `pwd`/bin
        chmod +x ./cf
        mv ./cf bin/
        echo export PATH="$PWD/bin:\$PATH" >> $BASH_ENV
        source $BASH_ENV
        cf install-plugin -f https://github.com/contraband/autopilot/releases/download/0.0.8/autopilot-linux

  cf_login: &cf_login
    run:
      command: make cf-login

  cf_login_prod: &cf_login_prod
    run:
      command: make cf-login-prod

  master_branch: &master_branch
    filters:
      branches:
        only:
          - master

jobs:
  build:
    <<: *elixir_image
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get --only prod
      - run: make -C clients/pay-client install
      - run: make -C assets setup
      - run: MIX_ENV=prod make build-release
      - persist_to_workspace:
          root: .
          paths:
            - Makefile
            - _build
            - manifest-dev.yml
            - manifest.yml

  test:
    <<: *elixir_image
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get --only prod
      - run: make -C clients/pay-client install
      - run: make -C assets setup
      - run: make frontend
      - run: make test

  manage-feature-deploys:
    <<: *undeploy_image
    steps:
      - checkout
      - *cf_install
      - *cf_login
      - run: make -C ci/provisioning setup-ci
      - run: make ci.setup-auth0
      - run: make ci.undeploy

  deploy:
    <<: *elixir_image
    steps:
      - attach_workspace:
          at: .
      - *cf_install
      - *cf_login
      - run: make deploy-dev

  deploy-prod:
    <<: *elixir_image
    steps:
      - attach_workspace:
          at: .
      - *cf_install
      - *cf_login_prod
      - run: make deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test
      - manage-feature-deploys
      - deploy:
          requires:
            - build
            - test

      - unlock-prod-deploy:
          <<: *master_branch
          type: approval
          requires:
            - build
            - test
            - deploy

      - deploy-prod:
          requires:
            - unlock-prod-deploy
