use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :pay, PayWeb.Endpoint, url: [host: "pay-f-swagger.apps.y.cld.gov.au", port: 80]

# Do not print debug messages in production
config :logger, level: :info

secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    raise """
    environment variable SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

config :pay, PayWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  secret_key_base: secret_key_base

config :bambora,
  api_username: System.get_env("BAMBORA_USERNAME"),
  api_password: System.get_env("BAMBORA_PASSWORD")

config :stripity_stripe,
  api_key: System.get_env("STRIPE_API_KEY")

# ## Using releases (Elixir v1.9+)
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start each relevant endpoint:

config :pay, PayWeb.Endpoint, server: true
