# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PayGovAu.Model.Payment do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :amount,
    :description,
    :email,
    :id,
    :metadata,
    :next_url,
    :reference,
    :return_url
  ]

  @type t :: %__MODULE__{
          :amount => integer() | nil,
          :description => String.t() | nil,
          :email => String.t() | nil,
          :id => String.t() | nil,
          :metadata => Map | nil,
          :next_url => String.t() | nil,
          :reference => String.t() | nil,
          :return_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PayGovAu.Model.Payment do
  import PayGovAu.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:metadata, :struct, PayGovAu.Model.Map, options)
  end
end
