# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PayGovAu.Model.Payment do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :amount,
    :description,
    :email,
    :id,
    :reference,
    :return_url
  ]

  @type t :: %__MODULE__{
          :amount => integer() | nil,
          :description => String.t() | nil,
          :email => String.t() | nil,
          :id => String.t() | nil,
          :reference => String.t() | nil,
          :return_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PayGovAu.Model.Payment do
  def decode(value, _options) do
    value
  end
end
